# Generated by Django 2.0.6 on 2021-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('pk_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=100, null=True)),
                ('jornada', models.CharField(max_length=100, null=True)),
                ('notas', models.TextField(null=True)),
            ],
        ),
    ]
